In [1]:
import numpy as np

Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix.

In [4]:
arr=np.arange(1,11)

In [6]:
matrix=arr.reshape(2,5)

In [7]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index.

In [9]:
arr2=np.arange(1,21)

In [13]:
result=arr2[5:15]
result

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above

In [15]:
print("Mean:", np.mean(arr2))
print("Median:", np.median(arr2))
print("Standard Deviation:", np.std(arr2))

Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398

Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting.

In [20]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
y = np.array([1, 2, 3, 4])
z=x-y
z

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

5. Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data. (Score: 2)

In [24]:
import pandas as pd

data= { 'Name':['John', 'Alice', 'Rahul', 'Anu', 'David',
             'Sara', 'Arun', 'Mary', 'Sam', 'Riya'],
        'Age':[25, 22, 28, 24, 30, 26, 23, 27, 29, 21],
        'gender': ['Male', 'Female', 'Male', 'Female', 'Male',
               'Female', 'Male', 'Female', 'Male', 'Femal']}

In [27]:
df = pd.DataFrame(data)
df

    Name  Age  gender
0   John   25    Male
1  Alice   22  Female
2  Rahul   28    Male
3    Anu   24  Female
4  David   30    Male
5   Sara   26  Female
6   Arun   23    Male
7   Mary   27  Female
8    Sam   29    Male
9   Riya   21   Femal

Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)

In [29]:
df['occupation'] = [
    'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer'
]
df

    Name  Age  gender  occupation
0   John   25    Male  Programmer
1  Alice   22  Female     Manager
2  Rahul   28    Male     Analyst
3    Anu   24  Female  Programmer
4  David   30    Male     Manager
5   Sara   26  Female     Analyst
6   Arun   23    Male  Programmer
7   Mary   27  Female     Manager
8    Sam   29    Male     Analyst
9   Riya   21   Femal  Programmer

In [35]:
abovethirty = df[df['Age'] >= 30]
abovethirty

    Name  Age gender occupation
4  David   30   Male    Manager

Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents. (Score:

In [44]:
df.to_csv('data_csv', index=False)

In [45]:
df=pd.read_csv('data_csv')

In [38]:
df

    Name  Age  gender  occupation
0   John   25    Male  Programmer
1  Alice   22  Female     Manager
2  Rahul   28    Male     Analyst
3    Anu   24  Female  Programmer
4  David   30    Male     Manager
5   Sara   26  Female     Analyst
6   Arun   23    Male  Programmer
7   Mary   27  Female     Manager
8    Sam   29    Male     Analyst
9   Riya   21   Femal  Programmer